### ISSUE TITLE
Question regarding testing

### ISSUE THREAD

**Issue by sb8244** [sb8244/RailsTutorial#1]
@robforman How much testing is too much with regards to HTML? I have always been in the camp of testing services super heavy and leaving the html be, for the most part. The Rails Tutorial goes super heavy on HTML testing (probably because there's nothing else to test). Would you be doing heavy HTML testing on live projects?

**Comment by robforman** [comment]
I don't typically test too much HTML. The Rails Tutorial is pretty heavy, and its worth practicing. I personally approach is to test my service objects thoroughly, the controllers that use them less (only happy path but not fringe cases), and the html that submits or display results even less. the exception would be key user events, such as purchase/upgrade/login.. which deserve an decent integration test like you're practicing.

**Comment by sb8244** [comment]
Awesome that sounds about right on point with my current ideas. Thanks for the feedback! I'm going to list things in the issues that I think would be good to figure out before starting sales. For example, I have an enhancement for oauth'ing via LinkedIn and storing profile basics.
